### ISSUE TITLE
Playlist URL schema different than single track URL schema 

### ISSUE THREAD

**Issue by jbwilliams1** [lagwagon/hidecloud#1]
```
Song href in playControls: /jesus-drone/coldplay-clocks-jesus-drone-remix?   in=essayessay/sets/indiebient
Song href in stream: /essayessay/sets/indiebient
```

Need to parse out the ?in= query string to know whether or not to skip playlists. Currently it saves the stream href as the hidden track key, so when it hits a hidden playlist it does not read properly from the playControls, and results in a non-skip

**Comment by ben-hunter-hansen** [comment]
[fixed](https://github.com/lagwagon/hidecloud/pull/3)
